export const postsApi = [
	{
		id: 1,
		category: "grief",
		image: "/img/pic-1.png",
		title: "Some Random Title",
		postedOn: "8 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
	{
		id: 2,
		category: "depression",
		image: "/img/pic-2.jpg",
		title: "Youdontloveme",
		postedOn: "9 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
	{
		id: 3,
		category: "goodbyes",
		image: "/img/pic-3.jpg",
		title: "Everthing's Going My Way",
		postedOn: "10 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
	{
		id: 4,
		category: "depression",
		image: "/img/pic-4.jpg",
		title: "I'll Be Fine",
		postedOn: "11 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
	{
		id: 5,
		category: "grief",
		image: "/img/pic-5.jpg",
		title: "Not My Regular Self",
		postedOn: "12 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
	{
		id: 6,
		category: "goodbyes",
		image: "/img/pic-6.jpeg",
		title: "Your Loss",
		postedOn: "13 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
	{
		id: 7,
		category: "goodbyes",
		image: "/img/pic-7.jpg",
		title: "No Way Home",
		postedOn: "15 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
	{
		id: 8,
		category: "grief",
		image: "/img/pic-8.jpg",
		title: "The Night Is Still Young",
		postedOn: "15 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
	{
		id: 9,
		category: "depression",
		image: "/img/pic-1.png",
		title: "The Devil Wears Prada",
		postedOn: "15 Jan, 2022",
		body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis, quasi optio laboriosam laudantium aliquid porro incidunt, esse nihil non a repudiandae cupiditate ex quam. Necessitatibus illo voluptatibus explicabo error atque.",
	},
];